name: Build and Release Singularity Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
          '25.06', '25.05', '25.04', '25.03', '25.02', '25.01',
          '24.12', '24.11', '24.10', '24.09', '24.08', '24.07', '24.06', '24.05', '24.04', '24.03', '24.02', '24.01',
          '23.12', '23.11', '23.10', '23.09', '23.08', '23.07', '23.06', '23.05', '23.04', '23.03', '23.02', '23.01',
        ]
        python: ['py3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container

      - name: Build Singularity image
        run: |
          sudo singularity build \
            --build-arg PYTHON=${{ matrix.python }} \
            --build-arg VERSION=${{ matrix.version }} \
            pytorch_${{ matrix.version }}_${{ matrix.python }}.sif Singularity.def

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compress Singularity image
        run: |
          zip -s 1900m -r -0 pytorch_${{ matrix.version }}_${{ matrix.python }}.zip pytorch_${{ matrix.version }}_${{ matrix.python }}.sif

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          make_latest: true
          files: |
            pytorch_${{ matrix.version }}_${{ matrix.python }}.z*
