name: Build and Release Singularity Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [
          '25.06', '25.05', '25.04', '25.03', '25.02', '25.01',
          '24.12', '24.11', '24.10', '24.09', '24.08', '24.07', '24.06', '24.05', '24.04', '24.03', '24.02', '24.01',
        ]
        python: ['py3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container

      - name: Build Singularity image
        run: |
          singularity build \
            --build-arg PYTHON=${{ matrix.python }} \
            --build-arg VERSION=${{ matrix.version }} \
            pytorch_${{ matrix.version }}_${{ matrix.python }}.sif Singularity.def

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          make_latest: true
          files: |
            pytorch_${{ matrix.version }}_${{ matrix.python }}.sif
